### PR TITLE
WIP: BinaryProvider.jl integration with Sundials v3.1.0

### PR DESCRIPTION
**Pull request by tshort**
DON'T MERGE!

This is a test, mainly to see if Appveyor works. This is an extension of #89.

BinDeps2 and BinaryProvider are still experimental. The API can still change, and this would break installs. It may be a while before this settles down enough to merge.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Should we instead go for Sundials 3.1 now that it's out?

**Comment by ChrisRackauckas** [comment]
What would we need to do to handle the API differences? Just run the Clang.jl wrapper again then fix up the interfaces? I can definitely do the last part. Never did the Clang.jl thing though but can give that a try.

**Comment by tshort** [comment]
Yes. Running the Clang.jl wrapper again should be the way to go. It’s been so long since I’ve done that, I can’t remember if there are other steps or gotcha’s.

**Comment by ChrisRackauckas** [comment]
Any updates?

**Comment by tshort** [comment]
Good timing for an update. BinDeps2 (now BinaryBuilder and BinaryProvider) is now quite usable and stable enough to give this a go. It includes a "wizard" that helps you build binaries. Last night, I did a test run with BinaryBuilder for Sundials 3.1.0. The results are here:

https://github.com/tshort/SundialsBuilderTest

The binary libraries are under Releases. To take this further, we may need to discuss the following:

* **Sundials version** -- What version do we want? v3.1.0 is the latest version of Sundials. To support that in Sundials.jl, someone will probably need to tweak the API based on the Sundials changes/additions.

* **Extra library features** -- Do we want to include extra features? For example, I've tried out a version with KLU compile in [here](https://github.com/tshort/SundialsKLUBuilder/). I did that because the Modia folks are interested in using Sundials with KLU (pinging @HildingElmqvist and @MartinOtter). I don't know what API changes that would require for Sundials.jl.

**Comment by MartinOtter** [comment]
> Extra library features -- Do we want to include extra features? For example, I've tried out a version with KLU compiled in here. I did that because the Modia folks are interested in using Sundials with KLU (pinging @HildingElmqvist and @MartinOtter). I don't know what API changes that would require for Sundials.jl.

This sounds very good. In Modia we use currently IDA and KINSOL from the Sundials suite with KLU for the sparse matrix handling A colleague has generated Windows DLLs. It would be very good, to get a cross-platform solution. In principal it is sufficient to provide the corresponding DLLs, since it is straitghtforward to provide a Julia interface manually for the few additional functions introduced by KLU. In Modia, we use:

```
function IDAKLU(ida_mem::Ptr{Void}, Neq::Int, NNZ::Int)
   ccall((:IDAKLU,libsundials_ida),Cint,(Ptr{Void},Cint,Cint),ida_mem,Neq,NNZ)
end

function IDAKLUSetOrdering(ida_mem::Ptr{Void}, ordering_choice::Int)
   ccall((:IDAKLUSetOrdering,libsundials_ida),Cint,(Ptr{Void},Cint),ida_mem,ordering_choice)
end

function IDASlsSetSparseJacFn(ida_mem::Ptr{Void})
    ccall((:IDASlsSetSparseJacFn,libsundials_ida),Cint,(Ptr{Void},Ptr{Void}),ida_mem, idasol_sjacc)
end
```
I followed the links in your comment, but could not figure out the location of the generated DLLs (I wanted to check whether your newly generated DLLs would work in Modia).

**Comment by ChrisRackauckas** [comment]
>Sundials version -- What version do we want? v3.1.0 is the latest version of Sundials. To support that in Sundials.jl, someone will probably need to tweak the API based on the Sundials changes/additions.

Yes, let's go directly to v3.1.0. I'll handle the API tweaks, but may need some help getting clang.jl to re-run.

>Extra library features -- Do we want to include extra features? For example, I've tried out a version with KLU compiled in here. I did that because the Modia folks are interested in using Sundials with KLU (pinging @HildingElmqvist and @MartinOtter). I don't know what API changes that would require for Sundials.jl.

Yes. I am terrible with setting up build systems, but I know how to wrap things into Julia really well now that I've gotten all of the Jacobian stuff working. If you get it built, I'll do the API changes. I think it would be nice to try and get the build working with BLAS, LAPACK, SuperLUMT, Hypre, and with OpenMP enabled? If that's not something that can be universal, can we have options at all? 

My main goal is that it should be cross-platform and work (on Windows as well) without any user intervention. Anything else is extra, but I hope that adding at least these is good. The extras would be MPI/PETSc, RAJA, and CUDA. It seems BinaryBuilder is much easier to use, so if you could leave those off for now but leave a comment on how to enable them that would be great. I don't plan on getting those setup for now, but down the road I have plans for a GSoC or undergrad project, not this summer, but later on for this. CUDA it's just too hard to keep up with the versions and RAJA is too new, but in two years I'll want to flip these switches (at least MPI and RAJA) and get full parallel Sundials working.

**Comment by tshort** [comment]
@MartinOtter, the repo with the KLU build did not finish building the binary libraries. I'll try that again tonight. It built them locally, but the fully-automated build didn't work the last time I tried it.

@ChrisRackauckas, tonight, I'll redo the regular Sundials build for v3.1.0. Once it looks set, we can talk about moving the builder repo to JuliaDiffEq. I'll plan to update the  `deps/build.jl` stuff, too.

I'll try to help with the Clang.jl build if you need it (it's been a while).

**Comment by tshort** [comment]
@ChrisRackauckas, I tweaked the builder repository:

https://github.com/tshort/SundialsBuilder

I labeled the release as `sundials-3.1.0`. If that looks okay to you, maybe we can move this repo to JuliaDiffEq.

This [build.jl](https://github.com/tshort/SundialsBuilder/releases/download/sundials-3.1.0/build.jl) file needs tweaked and inserted into `deps/build.jl`. Is this PR branch the best starting point for that (Sundials v2.7.0), or is master better?

**Comment by ChrisRackauckas** [comment]
>I labeled the release as sundials-3.1.0. If that looks okay to you, maybe we can move this repo to JuliaDiffEq.

Yup. Do you have sufficient permissions? I think so because of DASKR.jl?

>This build.jl file needs tweaked and inserted into deps/build.jl. Is this PR branch the best starting point for that (Sundials v2.7.0), or is master better?

I think it would be easier to start from what you have on this branch mostly because it's already setup with BinaryBuilder.

**Comment by tshort** [comment]
@MartinOtter, see the following release for binary libraries for Sundials+KLU:

https://github.com/tshort/SundialsKLUBuilder/releases/tag/sundials-3.1.0

The fully automated Travis build didn't work, so I uploaded the built binaries by hand. You can try downloading them manually, and/or you can try integrating the [build.jl](https://github.com/tshort/SundialsBuilder/releases/download/sundials-3.1.0/build.jl) into Modia's `deps/build.jl` to automate downloads.

**Comment by tshort** [comment]
The repo move worked:

https://github.com/JuliaDiffEq/SundialsBuilder

I'll start work on updating this branch.

**Comment by tshort** [comment]
@ChrisRackauckas, I updated `deps/build.jl`, and it seems to run and install the correct libraries. Tests are failing for me locally. It may be at a point where you want to take a look.

**Comment by ChrisRackauckas** [comment]
Notes:

1) Add BinaryProvider to REQUIRE
2) Change URLs

**Comment by ChrisRackauckas** [comment]
After checking out master on BinaryProvider.jl:

```julia
julia> Pkg.build("Sundials")
INFO: Building Sundials
"1st" = "1st"
INFO: Directory C:\Users\Chris\.julia\v0.6\Sundials\deps\usr\bin does not exist!
INFO: Downloading https://github.com/tshort/SundialsBuilder/releases/download/sundials-3.1.0/Sundial
s.x86_64-w64-mingw32.tar.gz to C:\Users\Chris\.julia\v0.6\Sundials\deps\usr\downloads\Sundials.x86_6
4-w64-mingw32.tar.gz...
INFO: No hash cache found
INFO: Calculated hash 0761e2236c9ab867d42616b633cd6f744cbf4c06c323dfcea79655741a37ab33 for file C:\U
sers\Chris\.julia\v0.6\Sundials\deps\usr\downloads\Sundials.x86_64-w64-mingw32.tar.gz
INFO: Installing C:\Users\Chris\.julia\v0.6\Sundials\deps\usr\downloads\Sundials.x86_64-w64-mingw32.
tar.gz into C:\Users\Chris\.julia\v0.6\Sundials\deps\usr

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive:

Extracting  .
Extracting  .\include
Extracting  .\include\cvode
Extracting  .\include\cvode\cvode_spils.h
Extracting  .\include\cvode\cvode_bandpre.h
Extracting  .\include\cvode\cvode.h
Extracting  .\include\cvode\cvode_direct.h
Extracting  .\include\cvode\cvode_impl.h
Extracting  .\include\cvode\cvode_diag.h
Extracting  .\include\cvode\cvode_bbdpre.h
Extracting  .\include\kinsol
Extracting  .\include\kinsol\kinsol.h
Extracting  .\include\kinsol\kinsol_direct.h
Extracting  .\include\kinsol\kinsol_spils.h
Extracting  .\include\kinsol\kinsol_bbdpre.h
Extracting  .\include\kinsol\kinsol_impl.h
Extracting  .\include\sunmatrix
Extracting  .\include\sunmatrix\sunmatrix_band.h
Extracting  .\include\sunmatrix\sunmatrix_sparse.h
Extracting  .\include\sunmatrix\sunmatrix_dense.h
Extracting  .\include\idas
Extracting  .\include\idas\idas.h
Extracting  .\include\idas\idas_impl.h
Extracting  .\include\idas\idas_spils.h
Extracting  .\include\idas\idas_bbdpre.h
Extracting  .\include\idas\idas_direct.h
Extracting  .\include\nvector
Extracting  .\include\nvector\nvector_serial.h
Extracting  .\include\cvodes
Extracting  .\include\cvodes\cvodes_direct.h
Extracting  .\include\cvodes\cvodes.h
Extracting  .\include\cvodes\cvodes_bandpre.h
Extracting  .\include\cvodes\cvodes_impl.h
Extracting  .\include\cvodes\cvodes_bbdpre.h
Extracting  .\include\cvodes\cvodes_spils.h
Extracting  .\include\cvodes\cvodes_diag.h
Extracting  .\include\arkode
Extracting  .\include\arkode\arkode_bandpre.h
Extracting  .\include\arkode\arkode_spils.h
Extracting  .\include\arkode\arkode_bbdpre.h
Extracting  .\include\arkode\arkode_direct.h
Extracting  .\include\arkode\arkode.h
Extracting  .\include\arkode\arkode_impl.h
Extracting  .\include\sundials
Extracting  .\include\sundials\sundials_spfgmr.h
Extracting  .\include\sundials\sundials_spbcgs.h
Extracting  .\include\sundials\sundials_spgmr.h
Extracting  .\include\sundials\sundials_config.h
Extracting  .\include\sundials\sundials_sptfqmr.h
Extracting  .\include\sundials\sundials_nvector.h
Extracting  .\include\sundials\sundials_fnvector.h
Extracting  .\include\sundials\sundials_band.h
Extracting  .\include\sundials\sundials_pcg.h
Extracting  .\include\sundials\sundials_version.h
Extracting  .\include\sundials\sundials_sparse.h
Extracting  .\include\sundials\sundials_matrix.h
Extracting  .\include\sundials\sundials_iterative.h
Extracting  .\include\sundials\sundials_dense.h
Extracting  .\include\sundials\sundials_types.h
Extracting  .\include\sundials\sundials_math.h
Extracting  .\include\sundials\sundials_direct.h
Extracting  .\include\sundials\sundials_fconfig.h
Extracting  .\include\sundials\sundials_linearsolver.h
Extracting  .\include\sunlinsol
Extracting  .\include\sunlinsol\sunlinsol_pcg.h
Extracting  .\include\sunlinsol\sunlinsol_dense.h
Extracting  .\include\sunlinsol\sunlinsol_spgmr.h
Extracting  .\include\sunlinsol\sunlinsol_sptfqmr.h
Extracting  .\include\sunlinsol\sunlinsol_band.h
Extracting  .\include\sunlinsol\sunlinsol_spbcgs.h
Extracting  .\include\sunlinsol\sunlinsol_spfgmr.h
Extracting  .\include\ida
Extracting  .\include\ida\ida_impl.h
Extracting  .\include\ida\ida_spils.h
Extracting  .\include\ida\ida_bbdpre.h
Extracting  .\include\ida\ida.h
Extracting  .\include\ida\ida_direct.h
Extracting  .\LICENSE
Extracting  .\logs
Extracting  .\logs\Sundials.log
Extracting  .\lib
Extracting  .\lib\libsundials_ida.dll.a
Extracting  .\lib\libsundials_sunlinsoldense.a
Extracting  .\lib\libsundials_sunlinsolspbcgs.dll
Extracting  .\lib\libsundials_sunlinsolpcg.a
Extracting  .\lib\libsundials_arkode.a
Extracting  .\lib\libsundials_sunmatrixdense.a
Extracting  .\lib\libsundials_cvodes.dll
Extracting  .\lib\libsundials_sunmatrixdense.dll.a
Extracting  .\lib\libsundials_nvecserial.a
Extracting  .\lib\libsundials_idas.dll.a
Extracting  .\lib\libsundials_sunlinsolspgmr.dll
Extracting  .\lib\libsundials_nvecserial.dll
Extracting  .\lib\libsundials_sunmatrixband.dll
Extracting  .\lib\libsundials_sunlinsolspfgmr.a

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\Chris\.julia\v0.6\Sundials\deps\usr\downloads\Sundials.x86_64-w64-mingw
32.tar.gz

Extracting  Sundials.x86_64-w64-mingw32.tar

Everything is Ok

Size:       14008320
Compressed: 3180480
Extracting  .\lib\libsundials_idas.dll
Extracting  .\lib\libsundials_sunlinsolband.a
Extracting  .\lib\libsundials_ida.dll
Extracting  .\lib\libsundials_cvode.dll.a
Extracting  .\lib\libsundials_cvodes.dll.a
Extracting  .\lib\libsundials_sunlinsoldense.dll
Extracting  .\lib\libsundials_sunlinsolband.dll
Extracting  .\lib\libsundials_sunlinsolsptfqmr.dll.a
Extracting  .\lib\libsundials_sunlinsolpcg.dll
Extracting  .\lib\libsundials_cvodes.a
Extracting  .\lib\libsundials_kinsol.dll.a
Extracting  .\lib\libsundials_sunlinsoldense.dll.a
Extracting  .\lib\libsundials_kinsol.a
Extracting  .\lib\libsundials_sunlinsolpcg.dll.a
Extracting  .\lib\libsundials_arkode.dll
Extracting  .\lib\libsundials_sunlinsolspfgmr.dll
Extracting  .\lib\libsundials_sunmatrixdense.dll
Extracting  .\lib\libsundials_sunlinsolsptfqmr.a
Extracting  .\lib\libsundials_nvecserial.dll.a
Extracting  .\lib\libsundials_idas.a
Extracting  .\lib\libsundials_arkode.dll.a
Extracting  .\lib\libsundials_sunlinsolspfgmr.dll.a
Extracting  .\lib\libsundials_sunmatrixband.dll.a
Extracting  .\lib\libsundials_ida.a
Extracting  .\lib\libsundials_cvode.dll
Extracting  .\lib\libsundials_kinsol.dll
Extracting  .\lib\libsundials_sunmatrixsparse.dll
Extracting  .\lib\libsundials_sunlinsolspbcgs.dll.a
Extracting  .\lib\libsundials_sunlinsolspgmr.a
Extracting  .\lib\libsundials_sunlinsolsptfqmr.dll
Extracting  .\lib\libsundials_sunlinsolspgmr.dll.a
Extracting  .\lib\libsundials_sunmatrixsparse.a
Extracting  .\lib\libsundials_sunmatrixband.a
Extracting  .\lib\libsundials_sunlinsolspbcgs.a
Extracting  .\lib\libsundials_cvode.a
Extracting  .\lib\libsundials_sunmatrixsparse.dll.a
Extracting  .\lib\libsundials_sunlinsolband.dll.a

Everything is Ok

Folders: 14
Files: 118
Size:       13901874
Compressed: 76800
"HERE" = "HERE"
INFO: Directory C:\Users\Chris\.julia\v0.6\Sundials\deps\usr\bin does not exist!
========================================[ ERROR: Sundials ]=========================================

LoadError: BinaryProvider.LibraryProduct("C:\\Users\\Chris\\.julia\\v0.6\\Sundials\\deps\\usr\\bin",
 String["libsundials_kinsol"]) is not satisfied, cannot generate deps.jl!
while loading C:\Users\Chris\.julia\v0.6\Sundials\deps\build.jl, in expression starting on line 45

====================================================================================================

==========================================[ BUILD ERRORS ]==========================================

WARNING: Sundials had build errors.

 - packages with build errors remain installed in C:\Users\Chris\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("Sundials")`
 - build a single package by running its `deps/build.jl` script

====================================================================================================
```

**Comment by ChrisRackauckas** [comment]
I don't have a bin, but I have .a's and .dll's in my lib folder. Is this just a pathing issue?

**Comment by tshort** [comment]
@ChrisRackauckas, that is the same path issue that I asked about on Slack. I'm not sure why, but BinaryProvider puts the library directory under `deps/bin` ([here](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/master/src/BinDepsIntegration.jl#L17) and [here](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/master/src/Prefix.jl#L124)). If I change those to `deps/lib`, it works. Either I've built the binaries wrong, or BinaryProvider is wrong. If I don't hear from Elliot today, I'll file an issue.

**Comment by ChrisRackauckas** [comment]
I rebased this onto master. It was pretty straightforward (just REQUIRE handling) so I just updated the branch.

**Comment by ChrisRackauckas** [comment]
Oops, looks like I choose the wrong BinDeps package to require... do we just need BinaryProvider? If so, then the BinDeps2 should be changed to that.

**Comment by ChrisRackauckas** [comment]
Simple commands run. Things which I know weren't changed aren't erroring, and things I know were changed are. Looks like it's good on the build side.

**Comment by ChrisRackauckas** [comment]
```julia
using Sundials, Compat

function f(t, y_nv, ydot_nv, user_data)
    u = convert(Vector, y_nv)
    du = convert(Vector, ydot_nv)
    du[1] = 10.0*(u[2]-u[1])
    du[2] = u[1]*(28.0-u[3]) - u[2]
    du[3] = u[1]*u[2] - (8/3)*u[3]
    return Sundials.CV_SUCCESS
end

const neq = 3
const t0 = 0.0
const t1 = 0.4
const tmult = 10.0
const nout = 12
const y0 = [1.0, 0.0, 0.0]
const reltol = 1e-4
const abstol = [1e-8, 1e-14, 1e-6]

cvode_mem = Sundials.CVodeCreate(Sundials.CV_ADAMS, Sundials.CV_FUNCTIONAL)
Sundials.@checkflag Sundials.CVodeInit(cvode_mem, f, t0, y0)
Sundials.@checkflag Sundials.CVodeSVtolerances(cvode_mem, reltol, abstol)

iout = 0
tout = t1
const t = [t0]

y = similar(y0)
while iout < nout
    flag = Sundials.CVode(cvode_mem, tout, y, t, Sundials.CV_NORMAL)
    println("T=", tout, ", Y=", y)
    iout += 1
    tout *= tmult
end
```

works!

**Pull request merged**
