### PR TITLE
WIP: Wrap Sundials v2.7.0

### PR DESCRIPTION
**Pull request by jgoldfar**
Unfortunately, this is in an inconsistent state due to https://github.com/JuliaDiffEq/Sundials.jl/issues/77#issuecomment-251235516 but I'll get it working... The wrappers generated by the previous wrap_sundials.jl produced a version which could be loaded but Pkg.test failed.

### CODE REVIEW

**Comment by alyst** [comment]
With minor modifications, I was able to make the current version of the `wrap_sundials.jl` parse Sundials 2.7.0 headers including ARKODE. The package is loadable and the tests pass (Julia 0.5, Clang 3.8.0, Clang.jl 0.1.0). Feel free to cherry-pick the commits from [alyst/Sundials.jl/sundials_2_7_0](https://github.com/alyst/Sundials.jl/tree/sundials_2_7_0) (the updated .jl wrappers are not commited).

**Comment by jgoldfar** [comment]
Wrappers are now functional enough to pass the unit tests. TODO, now or later:

* [] Clear up overwritten method warnings

* [] Update wrap_sundials.jl to work with Clang.jl master (turns out this was the issue) in case https://github.com/ihnorton/Clang.jl/pull/160 and/or https://github.com/ihnorton/Clang.jl/pull/153 provide performance and/or safety improvements.

**Comment by ChrisRackauckas** [comment]
It looks like the Windows builds fail since it can't find the binary. Does it need to be uploaded somewhere?

**Comment by jgoldfar** [comment]
Ues; coveralls left a mess there but see https://github.com/JuliaDiffEq/Sundials.jl/pull/89#issuecomment-251461607 Wondering where Travis results went? Looking at the build.jl script, it seems as though this is something @tkelman did in the past? I've never had any luck with Windows builds...

**Comment by ChrisRackauckas** [comment]
Hey @tkelman do you have any input on updating the build script for Windows?

**Comment by ChrisRackauckas** [comment]
Bumping to try and get @tkelman 's input.

**Comment by tkelman** [comment]
I don't have time to work on this. What have you tried?

**Comment by ChrisRackauckas** [comment]
I'm just looking for pointers on how you did this before. Is it:

1. Build Sundials on a Windows machine.
2. Host pre-binaries.

If so, I just have a question about 2. I am not sure how to host it. The URL is currently:

```
https://cache.julialang.org/https://bintray.com/artifact/download/tkelman/generic/$sundialsver.7z
```

I looked into Bintray and there's no free plan, right? Is there something free like it that I should use (SourceForge)? Or should I build the binary and send it over to you to add to some Julia Bintray account?

**Comment by tkelman** [comment]
How you do 1 matters a lot more than how you do 2. There are free plans for bintray, but their UI is kind of annoying to work out how to just upload a file. Don't use sourceforge, it's awful and unreliable. If you can't figure out how to get bintray to work, a better option is probably just attaching files to github releases.

**Comment by ChrisRackauckas** [comment]
>How you do 1 matters a lot more than how you do

I was just going to follow their Windows installation guide to a tee (it's just steps for building using Visual Studio). Is this a word of caution against doing that?

>There are free plans for bintray, but their UI is kind of annoying to work out how to just upload a file. Don't use sourceforge, it's awful and unreliable. If you can't figure out how to get bintray to work, a better option is probably just attaching files to github releases.

Knowing that there's a way to make it work for free is enough. I'll keep poking at it.

**Comment by tkelman** [comment]
No, don't use Visual Studio. If Julia itself were built with Visual Studio then that would be a good idea. It isn't, so it isn't. Should use a compilation environment as close as possible to what's used for Julia itself for the most reliable results. Or you could look into using the opensuse build service with a cross-compiled version of the library via WinRPM, which a few other packages do.

**Comment by ChrisRackauckas** [comment]
Thanks for the tips. I'll take a crack at getting it to build using the Opensuse build service.

**Comment by tshort** [comment]
I've created a fork of this PR [here](https://github.com/JuliaDiffEq/Sundials.jl/tree/bindeps2) that works with binaries generated by [BinDeps2](https://github.com/staticfloat/BinDeps2.jl) using [this build script](https://github.com/tshort/Sundials.jl.build). Sundials tests pass on 64-bit Windows, Mac, and Linux. 

BinDeps2 is still pre-alpha software though, so we are in a holding pattern until it matures more. For example, we still need 32-bit library support. The API could completely change on us.

@staticfloat's doing great work with BinDeps2. Sundials was quite easy to build with it. Given that it is so easy to build, we might consider supporting different flavors of Sundials given that Sundials has many build options (KLU solver, MPI support, etc.).

When it does settle down, this branch will need to be merged with master, so that might be some work given the divergence.

**Comment by ChrisRackauckas** [comment]
Would it make Windows require a compiler?

**Comment by tshort** [comment]
No compiler is needed to build Sundials.jl on Windows or the other platforms supportedby BinDeps2 (Mac, x86_64 Linux, and a few other flavors of Linux). Binary versions of the Sundials library are downloaded that are appropriate for the current platform. That has a nice side effect that Travis tests should run faster. The builds of these binaries happens in a docker container, but that's done separately.

**Comment by ChrisRackauckas** [comment]
Superseded via https://github.com/JuliaDiffEq/Sundials.jl/pull/149, but good work because that PR utilized many ideas from here!

**Pull request closed without merging**
