### PR TITLE
Prepare to use Sundials artifacts

### PR DESCRIPTION
**Pull request by ViralBShah**
This sets the min Julia version to 1.3. It pulls in Sundials_jll which depends on SuiteSparse_jll and OpenBLAS_jll.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@giordano You had said something about how this could be done in a way that is compatible with BinaryProvider. Do you have a pointer to a project that does it?

**Comment by ViralBShah** [comment]
Failure seems to be in #224.

**Comment by giordano** [comment]
I don't know if anyone implemented it yet, but the idea is to depend on both Sundials_jll.jl and BinaryProvider.jl, and add a deps/build.jl which if VERSION >= v"1.3" would load the jll package, otherwise would load the script to install the tarballs using BinaryProvider. This is akin to what [FFTW.jl](https://github.com/JuliaMath/FFTW.jl) does to provide either FFTW or MKL

**Comment by ViralBShah** [comment]
Ok, makes sense. I'll try it out.

**Comment by ViralBShah** [comment]
@ChrisRackauckas I think we can perhaps stay with 1.3 and above, given that multi-threading is getting widely used in the DiffEq ecosystem. Is it ok to merge this, or are there other considerations?

**Comment by ChrisRackauckas** [comment]
Interesting that this works, since it fails for me locally:

```julia
Mass Matrix: Error During Test at C:\Users\accou\.julia\dev\Sundials\test\runtests.jl:33
  Got exception outside of a @test
  LoadError: ArgumentError: unsafe_wrap: pointer 3531646E00000009 is not properly aligned to 8 bytes
  Stacktrace:
   [1] convert at .\pointer.jl:84 [inlined]
   [2] massmat(::Float64, ::Ptr{Sundials._generic_SUNMatrix}, ::Sundials.FunJac{ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,Nothing,DiffEqBase.NullParameters,Array{Float64,2},Nothing,Array{Float64,1},Nothing,Nothing,Nothing}, ::Ptr{Sundials._generic_N_Vector}, ::Ptr{Sundials._generic_N_Vector}, ::Ptr{Sundials._generic_N_Vector}) at C:\Users\accou\.julia\dev\Sundials\src\common_interface\function_types.jl:147
   [3] __ARKode at C:\Users\accou\.julia\dev\Sundials\src\wrapped_api\arkode.jl:363 [inlined]
   [4] ARKode(::Sundials.Handle{Sundials.ARKODEMem}, ::Float64, ::Sundials.NVector, ::Array{Float64,1}, ::Int32) at C:\Users\accou\.julia\dev\Sundials\src\wrapped_api\arkode.jl:368
   [5] solver_step(::Sundials.ARKODEIntegrator{Sundials.NVector,DiffEqBase.NullParameters,Sundials.Handle{Sundials.ARKODEMem},ODESolution{Float64,2,Array{Array{Float64,1},1},Array{Array{Float64,1},1},Dict{Symbol,Float64},Array{Float64,1},Nothing,ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},ARKODE{:Newton,:Dense,:Dense,Sundials.Implicit,Nothing,Nothing,Nothing,Nothing},DiffEqBase.HermiteInterpolation{Array{Float64,1},Array{Array{Float64,1},1},Array{Array{Float64,1},1}},DiffEqBase.DEStats},ARKODE{:Newton,:Dense,:Dense,Sundials.Implicit,Nothing,Nothing,Nothing,Nothing},ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Sundials.FunJac{ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,Nothing,DiffEqBase.NullParameters,Array{Float64,2},Nothing,Array{Float64,1},Nothing,Nothing,Nothing},Nothing,Sundials.DEOptions{DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},CallbackSet{Tuple{},Tuple{}},Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE)},Array{Float64,1},Tuple{Int64},Array{Float64,1},Sundials.LinSolHandle{Sundials.Dense},Sundials.MatrixHandle{Sundials.DenseMatrix},Sundials.LinSolHandle{Sundials.Dense},Sundials.MatrixHandle{Sundials.DenseMatrix},Nothing}, ::Float64) at C:\Users\accou\.julia\dev\Sundials\src\common_interface\solve.jl:1101
   [6] solve!(::Sundials.ARKODEIntegrator{Sundials.NVector,DiffEqBase.NullParameters,Sundials.Handle{Sundials.ARKODEMem},ODESolution{Float64,2,Array{Array{Float64,1},1},Array{Array{Float64,1},1},Dict{Symbol,Float64},Array{Float64,1},Nothing,ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},ARKODE{:Newton,:Dense,:Dense,Sundials.Implicit,Nothing,Nothing,Nothing,Nothing},DiffEqBase.HermiteInterpolation{Array{Float64,1},Array{Array{Float64,1},1},Array{Array{Float64,1},1}},DiffEqBase.DEStats},ARKODE{:Newton,:Dense,:Dense,Sundials.Implicit,Nothing,Nothing,Nothing,Nothing},ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Sundials.FunJac{ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,Nothing,DiffEqBase.NullParameters,Array{Float64,2},Nothing,Array{Float64,1},Nothing,Nothing,Nothing},Nothing,Sundials.DEOptions{DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},CallbackSet{Tuple{},Tuple{}},Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE)},Array{Float64,1},Tuple{Int64},Array{Float64,1},Sundials.LinSolHandle{Sundials.Dense},Sundials.MatrixHandle{Sundials.DenseMatrix},Sundials.LinSolHandle{Sundials.Dense},Sundials.MatrixHandle{Sundials.DenseMatrix},Nothing}) at C:\Users\accou\.julia\dev\Sundials\src\common_interface\solve.jl:1145
   [7] #__solve#22(::Base.Iterators.Pairs{Symbol,Float64,Tuple{Symbol,Symbol},NamedTuple{(:abstol, :reltol),Tuple{Float64,Float64}}}, ::typeof(DiffEqBase.__solve), ::ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem}, ::ARKODE{:Newton,:Dense,:Dense,Sundials.Implicit,Nothing,Nothing,Nothing,Nothing}, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at C:\Users\accou\.julia\dev\Sundials\src\common_interface\solve.jl:12
   [8] #__solve at .\none:0 [inlined] (repeats 5 times)
   [9] #solve_call#442(::Base.Iterators.Pairs{Symbol,Float64,Tuple{Symbol,Symbol},NamedTuple{(:abstol, :reltol),Tuple{Float64,Float64}}}, ::typeof(DiffEqBase.solve_call), ::ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem}, ::ARKODE{:Newton,:Dense,:Dense,Sundials.Implicit,Nothing,Nothing,Nothing,Nothing}) at C:\Users\accou\.julia\packages\DiffEqBase\E16PL\src\solve.jl:38
   [10] #solve_call at .\none:0 [inlined]
   [11] #solve#443 at C:\Users\accou\.julia\packages\DiffEqBase\E16PL\src\solve.jl:57 [inlined]
   [12] (::DiffEqBase.var"#kw##solve")(::NamedTuple{(:abstol, :reltol),Tuple{Float64,Float64}}, ::typeof(solve), ::ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DiffEqBase.NullParameters,ODEFunction{true,var"#mm_f#32"{Array{Float64,1},Array{Float64,2}},Array{Float64,2},var"#mm_analytic#34",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem}, ::ARKODE{:Newton,:Dense,:Dense,Sundials.Implicit,Nothing,Nothing,Nothing,Nothing}) at .\none:0
   [13] top-level scope at C:\Users\accou\.julia\dev\Sundials\test\common_interface\mass_matrix.jl:32
   [14] include at .\boot.jl:328 [inlined]
   [15] include_relative(::Module, ::String) at .\loading.jl:1105
   [16] include(::Module, ::String) at .\Base.jl:31
   [17] include(::String) at .\client.jl:424
   [18] top-level scope at C:\Users\accou\.julia\dev\Sundials\test\runtests.jl:33
   [19] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
   [20] top-level scope at C:\Users\accou\.julia\dev\Sundials\test\runtests.jl:33
   [21] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
   [22] top-level scope at C:\Users\accou\.julia\dev\Sundials\test\runtests.jl:26
   [23] include at .\boot.jl:328 [inlined]
   [24] include_relative(::Module, ::String) at .\loading.jl:1105
   [25] include(::Module, ::String) at .\Base.jl:31
   [26] include(::String) at .\client.jl:424
   [27] top-level scope at none:6
   [28] eval(::Module, ::Any) at .\boot.jl:330
   [29] exec_options(::Base.JLOptions) at .\client.jl:263
   [30] _start() at .\client.jl:460
  in expression starting at C:\Users\accou\.julia\dev\Sundials\test\common_interface\mass_matrix.jl:32

Test Summary:    | Pass  Error  Total
Common Interface |   38      2     40
  CVODE          |   23            23
  ARKODE         |    3             3
  IDA            |    7             7
  Jacobians      |           1      1
  Callbacks      |    4             4
  Iterator       |              No tests
  Errors         |    1             1
  Mass Matrix    |           1      1
ERROR: LoadError: Some tests did not pass: 38 passed, 0 failed, 2 errored, 0 broken.
in expression starting at C:\Users\accou\.julia\dev\Sundials\test\runtests.jl:25
ERROR: Package Sundials errored during testing
```

**Comment by ViralBShah** [comment]
Are you on 64-bit windows? Does the failing test call blas/lapack by any chance?

**Comment by ChrisRackauckas** [comment]
64-bit Windows. I am not sure if Sundials has a size check for whether to BLAS or not, but the tests are all small ODEs. If it doesn't check size, then it would BLAS in the factorization.

**Pull request closed without merging**
