### PR TITLE
Move function wrappers into simplified interface

### PR DESCRIPTION
**Pull request by jgoldfar**
Move function wrappers into simplified interface and remove function argument (replace by closures) to fix tests on git master. Not sure if this is the "correct" way to do this compared to the comment on https://github.com/JuliaLang/julia/pull/13412, but it does work.

Update: It works for simple cases, but not when the RHS is a closure.

### CODE REVIEW

**Comment by jgoldfar** [comment]
This is definitely a breaking change between 0.4 and the latest master, so I suppose some version check will be needed for these changes. Not sure what is the recommended way to implement that.

**Comment by ChrisRackauckas** [comment]
>Update: It works for simple cases, but not when the RHS is a closure.

Is that statement for v0.4? It should work on v0.5 since anonymous functions are generic in that case. But if closures aren't working with it in v0.5, I'd count that as a non-starter since I can point to a lot of examples where people are using closures to put in parameters. Anyways, this is not actionable unless tests pass. You should relabel this WIP if you plan on continuing this, or close.

@alyst was this touched in #67? I don't recall seeing changes to the function wrappers. Is this affected by the changes?

**Comment by alyst** [comment]
@ChrisRackauckas It was somewhat touched, in the sense that `userdata` parameter was declared to be of type `Any` directly by the wrapper generator, so simplified interface implementation had to be updated and now it should allow Julian closures, i.e. passing Julia user data to the Julia function through the low-level wrapper.

I'm not sure we need to move the wrapper functions into the bodies of the simplified interface function.

Maybe it's worth investigating what is the overhead of the current wrapper implementation and whether there are ways to improve it (e.g. parameterize UserDataAndFunction by the type of user data and make it immutable). I left it out of the #67 scope.

CVODE/IDA allows specifying the other user functions, e.g. `IDADlsSetDenseJacFn()` (see `ida_Roberts_dns.jl` example). Currently they are not supported.

**Comment by ChrisRackauckas** [comment]
Sounds like this is relevant to the discussion JuliaDiffEq/Roadmap#2

**Comment by jgoldfar** [comment]
I've been following Julia development and using v0.5/master in my work for a while, but haven't touched the Sundials portion for a bit. I believe the issue with ccallable closures was present in v0.4 and has been (at least partially) resolved recently; the change in this PR fixed some issues on the then-current master, but not all.

**Comment by jgoldfar** [comment]
See also https://github.com/JuliaLang/julia/issues/1096

**Comment by ChrisRackauckas** [comment]
Was it not resolved by JuliaLang/julia#13412 now that anonymous functions are all generic?

**Comment by jgoldfar** [comment]
No: the issue I was trying to work around was caused by that; Ref{Function} no longer made sense. Ptr{Void} does though.

**Comment by ChrisRackauckas** [comment]
I see.

**Comment by ChrisRackauckas** [comment]
No longer relevant.

**Pull request closed without merging**
