### PR TITLE
Enable precompilation

### PR DESCRIPTION
**Pull request by alyst**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This seems reasonable, but we may want more test coverage before merging it to make sure no standard use-cases segfault because of precompilation.

**Comment by alyst** [comment]
To my understanding turning on precompilation may break the package run-time initialization if `.jl` files contain any runtime-dependent variable initialization. These commands have to be moved into `__init__()`, but AFAIK Sundials doesn't contain such code. Besides that, the compiled code should be the same with/without precompilation, so no additional segfaults.

**Comment by ChrisRackauckas** [comment]
There are other things that can cause issues with precompilation, such as inlining Bigs of any sort. However, this is definitely something Sundials should have. Likewise, since we just tagged the other version, I would say give it a try and add this to the list of things included in the minor tag. Since that version may have breaking changes anyways, it is probably a good idea to get this working at the same time.

I'll wait for an opinion from @acroy

**Comment by acroy** [comment]
I don't see a problem with allowing precompilation. It's also easy to reverse if there are any issued related to it ...

**Comment by ChrisRackauckas** [comment]
Alright then lets give it a try.

**Pull request merged**
