### PR TITLE
[WIP] Sundials 3.1

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
This PR builds off of https://github.com/JuliaDiffEq/Sundials.jl/pull/140 and includes the API changes for Sundials 3.1

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This is using @jgoldfar's `wrap_sundials.jl` from though there's a comment that it may not be updated? 

https://github.com/JuliaDiffEq/Sundials.jl/pull/89#issuecomment-251461607

I'll give it a try because it looks like from the PR it is changed, but let me know if there's a newer one I should start from.

**Comment by jgoldfar** [comment]
Thanks for picking this up! I think my comment on the previous PR is out of date

**Comment by ChrisRackauckas** [comment]
Thanks! I'll see if I can get the Clang.jl thing to work. Never done it though. Fingers crossed.

**Comment by tshort** [comment]
I just updated `deps/build.jl` to download new libraries. This should now work with an unmodified BinaryProvider on windows.

**Comment by ChrisRackauckas** [comment]
Sweet. I got a simple Lorenz test and Roberts working. I had to manually modify a few things in the API though with the new linear solver stuff, so I'll need to modify wrap_sundials.jl a little... but I got it from here. Thanks @tshort and @jgoldfar!

**Comment by ChrisRackauckas** [comment]
Everything's updated and tests pass. I just need to create handles for the new matrix and linear solver objects and we're good to go.

**Comment by ChrisRackauckas** [comment]
Travis is passing but just isn't running on Mac for any repo tonight. Our AppVeyor will only run on master, and locally things are passing on Linux and Windows, so I'm going to pull to master to get AppVeyor running and let Mac catch up. Good stuff everyone!

**Pull request merged**
